# Generated by Django 3.0.2 on 2020-01-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framerest', '0002_registrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='con_password',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
