# Generated by Django 3.0.2 on 2020-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framerest', '0003_registrationform_con_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
