# Generated by Django 3.0.2 on 2020-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framerest', '0004_auto_20200122_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='con_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
